# Codecademy
# Fun Fact: Codecademy is for everyone!

print("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC                     ")
print("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC                     ")
print("CCCC                       CCCC                     ")
print("CCCC                       CCCC                     ")
print("CCCC                       CCCC                     ")
print("CCCC        CCCCCCC        CCCC                     ")
print("CCCC      CCCCCCCCCCC      CCCC                     ")
print("CCCC     CCC               CCCC                     ")
print("CCCC     CCC               CCCC                     ")
print("CCCC     CCC               CCCC                     ")
print("CCCC     CCC               CCCC                     ")
print("CCCC     CCC               CCCC                     ")
print("CCCC      CCCCCCCCCCC      CCCC                     ")
print("CCCC        CCCCCCC        CCCC                     ")
print("CCCC                       CCCC                     ")
print("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC     ****************")
print("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC     ****************")